### ISSUE TITLE
IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first

### ISSUE THREAD

**Issue by eileenfan** [numixproject/com.numix.calculator#48]
//package name: com.numix.calculator
//version: 2.2
 java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
 	at android.view.ViewGroup.addViewInner(ViewGroup.java:3509)
 	at android.view.ViewGroup.addView(ViewGroup.java:3380)
 	at android.support.v4.view.ViewPager.addView(ViewPager.java:1304)
 	at android.view.ViewGroup.addView(ViewGroup.java:3325)
 	at android.view.ViewGroup.addView(ViewGroup.java:3301)
 	at com.numix.calculator.CalculatorPageAdapter.instantiateItem(CalculatorPageAdapter.java:21)
 	at android.support.v4.view.PagerAdapter.instantiateItem(PagerAdapter.java:110)
 	at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:832)
 	at android.support.v4.view.ViewPager.populate(ViewPager.java:1016)
 	at android.support.v4.view.ViewPager.populate(ViewPager.java:914)
 	at android.support.v4.view.ViewPager$3.run(ViewPager.java:244)
 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
 	at android.view.Choreographer.doCallbacks(Choreographer.java:562)
 	at android.view.Choreographer.doFrame(Choreographer.java:531)
 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
 	at android.os.Handler.handleCallback(Handler.java:730)
 	at android.os.Handler.dispatchMessage(Handler.java:92)
 	at android.os.Looper.loop(Looper.java:137)
 	at android.app.ActivityThread.main(ActivityThread.java:5103)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:525)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
 	at dalvik.system.NativeStart.main(Native Method)

**Comment by codewrangler1** [comment]
Anybody find a solution to this?...I am having the same issue since updating to AS3...thanks!

**Comment by WonderProgrammer** [comment]
above the addView(): 
`ViewGroup parent = ((ViewGroup)your_view.getParent())
if (parent!=null){
parent.removeView(your_view);
}`
